version: '3'

services:
  api:
    build: .
    container_name: api
    command: sh -c 'yarn prisma migrate deploy && yarn prisma generate && yarn start:dev'
    ports:
      - '3333:3333'
      - '5555:5555'
      - '5000:5555'
    volumes:
      - .:/usr/app/foxtravels
    links:
      - db
    depends_on:
      - db

  db:
    container_name: foxtravels-db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=foxtravels
      - POSTGRES_PASSWORD=foxtravelsdocker
      - POSTGRES_DB=foxtravels
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
